services:
  postgres:
    image: postgres:16
    container_name: gestionate_postgres
    environment:
      POSTGRES_DB: gestionate_db
      POSTGRES_USER: gestionate_user
      POSTGRES_PASSWORD: gestionate_password
    ports:
      - "5433:5432"
    volumes:
      - gestionate_pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: gestionate_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gestionate.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '8082:80'
    depends_on:
      - postgres

volumes:
  gestionate_pgdata:
