package com.gestionate.backend.reports.model;

public enum IncidentTypeName {
    RESIDUOS_ORGANICOS,
    DESMONTE_RESIDUOS_CONSTRUCCION,
    RESIDUOS_PELIGROSOS_QUIMICOS,
    MUEBLES_OBJETOS_VOLUMINOSOS,
    RESIDUOS_COMERCIALES,
    RESIDUOS_AREAS_PUBLICAS_VERDES,
    OTRO_TIPO_RESIDUO
}
